version: "3"
services:
  otel-web-client:
    image: xiaoweiwang/otel-web-client:latest
    environment:
      - JVM_OPTS=-Dotel.traces.exporter=otlp,logging -Dotel.metrics.exporter=otlp -Dotel.exporter.otlp.endpoint=http://localhost:4317 -Dotel.service.name=user-client
    ports:
        - "8080:8080"
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"



